version: "2"
services:
   chicv:
    build:  .
    hostname: web-only
    ports:
     - "18080:80"
     - "18081:18081"
     - "18082:18082"
     - "18083:18083"
     - "18084:18084"
    volumes:
      - "~/Code:/home/chicv/Code"
      - "./Cmd:/home/chicv/Cmd"
      - "./sites-enabled:/etc/nginx/sites-enabled"
    mem_limit: "2g"
    memswap_limit: 2g
    privileged: true
    tty: true
    cpu_shares: 73
    cpuset: 0,1
    container_name: chicv-web
    dns: 8.8.8.8
    ulimits:
     nproc: 65535
     nofile:
      soft: 20000
      hard: 40000
