version: '2.1'

services:
  vcg:
    image: vcg
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 6060:6060
      - 9229:9229
    ## set your startup file here
    command: node --inspect app.js